Fix bag branch
olegdzhufer/Dragee pull request #19
Opened 2024-06-28 10:56 UTC by IgorIoT13

2024-07-02 19:04 UTC, VladVanyuk requested changes
Make changes described in comment blocks. @IgorIoT13

2024-07-02 19:04 UTC, VladVanyuk commented on Dragee.ino
Move to another file what is not necessary.

2024-07-02 19:04 UTC, VladVanyuk commented on Enc.h
Deleted?

2024-07-02 19:04 UTC, VladVanyuk commented on pins.h
Delete RelayPIN  and other TESTs values

2024-07-02 19:04 UTC, VladVanyuk commented on relay.h
bool* pidState ;
Whats your point? That's make no sense

2024-07-02 19:04 UTC, VladVanyuk commented on secrets.h
Make dynamic and changeable wifi_mode

2024-07-02 19:04 UTC, VladVanyuk commented on serverHost.h
Why includes are out of range of #ifdef ?

2024-07-02 19:04 UTC, VladVanyuk commented on settings.h
Add 
min_heat_temp = 30;

2024-07-02 19:04 UTC, VladVanyuk commented on countUpTimer.h
Are you sure it will not be necessary in future?

2024-07-03 07:59 UTC, IgorIoT13 commented on secrets.h
Done

2024-07-03 07:59 UTC, IgorIoT13 commented on settings.h
Done

2024-07-03 08:00 UTC, IgorIoT13 commented on countUpTimer.h
Yes

2024-07-03 08:01 UTC, IgorIoT13 commented on Enc.h
Yes.
Debug realize in setting.h

2024-07-03 08:02 UTC, IgorIoT13 commented on pins.h
Done

2024-07-04 06:32 UTC, IgorIoT13 commented on serverHost.h
Done

2024-07-04 07:30 UTC, IgorIoT13 commented on Dragee.ino
Done?

2024-07-04 07:30 UTC, IgorIoT13 commented on Enc.h
Done

2024-07-06 18:56 UTC, VladVanyuk approved these changes

2024-07-06 18:56 UTC, merged